; Uploads
upload_max_filesize = 128M
post_max_size       = 128M
max_file_uploads    = 20

; Memoria y ejecucion
memory_limit        = 1024M
max_execution_time  = 300
max_input_time      = 300
max_input_vars      = 3000

; Errores (prod)
display_errors          = Off
display_startup_errors  = Off
log_errors              = On
error_log               = /proc/self/fd/2

; Timezone
date.timezone = Europe/Madrid

; OPcache prod
opcache.enable                  = 1
opcache.enable_cli              = 0
opcache.memory_consumption      = 256
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files   = 20000
opcache.validate_timestamps     = 1
opcache.revalidate_freq         = 2
opcache.fast_shutdown           = 1
opcache.jit                     = off
opcache.jit_buffer_size         = 0

; Realpath cache
realpath_cache_size = 4096k
realpath_cache_ttl  = 600

; Sesiones
session.cookie_httponly = 1
session.cookie_secure   = 1
session.cookie_samesite = "Lax"

; Hide PHP
expose_php = Off
